<?php
 /* DoYouHaoBaby Framework Config File,Do not to modify this file! */ 
 return array (
  'DB_PASSWORD' => '123456',
  'DB_PREFIX' => 'dyhbblogx_',
  'DB_NAME' => 'dyhbblogxv201222',
  'DB_CACHE_FIELDS' => true,
  'DB_CACHE' => true,
  'DB_CACHE_TIME' => 86400000000,
  'APP_DEBUG' => true,
  'SHOW_RUN_TIME' => true,
  'SHOW_DB_TIMES' => true,
  'SHOW_GZIP_STATUS' => true,
  'RBAC_DATA_PREFIX' => 'rbac_data_prefix_x_doyouhaobaby_',
  'COOKIE_PREFIX' => 'x_doyouhaobaby_',
  'RBAC_ROLE_TABLE' => 'role',
  'RBAC_USERROLE_TABLE' => 'userrole',
  'RBAC_ACCESS_TABLE' => 'access',
  'RBAC_NODE_TABLE' => 'node',
  'USER_AUTH_ON' => true,
  'USER_AUTH_TYPE' => 1,
  'USER_AUTH_KEY' => 'auth_id',
  'ADMIN_USERID' => '1',
  'ADMIN_AUTH_KEY' => 'administrator',
  'USER_AUTH_MODEL' => 'user',
  'AUTH_PWD_ENCODER' => 'md5',
  'USER_AUTH_GATEWAY' => 'public/login',
  'NOT_AUTH_MODULE' => 'public',
  'REQUIRE_AUTH_MODULE' => '',
  'NOT_AUTH_ACTION' => '',
  'REQUIRE_AUTH_ACTION' => '',
  'GUEST_AUTH_ON' => false,
  'GUEST_AUTH_ID' => 0,
  'RBAC_ERROR_PAGE' => '',
  'TIME_ZONE' => 'Asia/Shanghai',
  'TEMPLATE_TAG_NOTE' => true,
  'APP_DEVELOP' => 0,
  'FRONT_TPL_DIR' => 'Default',
  'ADMIN_TPL_DIR' => 'Default',
  'NOT_ALLOWED_EMPTYCONTROL_VIEW' => true,
  'COOKIE_LANG_TEMPLATE_INCLUDE_APPNAME' => false,
  'DB_HOST' => 'localhost',
  'DB_USER' => 'root',
)
?>