<?dyhb
return array(
	'START_GZIP'=>TRUE,// Gzip压缩
	'APP_DEBUG'=>FALSE,// 项目DEBUG调式
	'DB_HOST'=>'localhost',// 数据库地址
	'DB_USER'=>'root',// 数据库用户名
	'DB_PASSWORD'=>'',// 数据库密码
	'DB_PREFIX'=>'doyouhaobaby_',// 数据库表前缀
	'DB_CHAR'=>'utf8',// 数据库编码
	'DB_NAME'=>'',// 数据库名字
	'DB_TYPE'=>'mysql',// 数据库类型
	'DB_SCHEMA'=>'',// 数据库SCHEMA
	'DB_PORT'=>3306,// 端口
	'DB_CACHE'=>FALSE,// 数据库查询是否缓存
	'DB_META_CACHED'=>TRUE,// 数据库元是否缓存
	'DB_DISTRIBUTED'=>FALSE,// 是否采用分布式
	'DB_RW_SEPARATE'=>FALSE,// 数据库读写是否分离主从式有效
	'DB_FIELDTYPE_CHECK'=>TRUE,// 是否进行数据库字段自动转化
	'DB_DSN'=>'mysql://username:password@localhost:3306/dbname',// 数据dsn解析
	'DB_PARAMS'=>array(),// 数据库连接参数
	'TEMPLATE_NOT_ALLOWS_FUNC'=>'echo,exit',// 系统不允许解析的函数-英文半角“,”隔开*
	'CACHE_LIFE_TIME'=>-1,// 模板编译缓存时间,单位秒,-1表示永不过期
	'THEME_SWITCH'=>TRUE,// 是否允许模板切换
	'TPL_DIR'=>'Default',// 模板默认主题
	'PHP_OFF'=>FALSE,// 是否允许PHP代码
	'TEMPLATE_TAG_NOTE'=>FALSE,// FALSE {if}X{/if}-<if>Y</if> | 注释版标签风格 TRUE <!--{if}-->X<!--{/if}-->-<!--<if>-->Y<!--</if>-->
	'TEMPLATE_SUFFIX'=>'.html',// 模板后缀
	'ERROR_PAGE'=>'',// 错误页面
	'SHOW_ERROR_MSG'=>TRUE,// 是否显示错误
	'TMPL_ACTION_ERROR'=>'public+success',// 默认错误跳转对应的模板文件
	'TMPL_ACTION_SUCCESS'=>'public+success',// 默认成功跳转对应的模板文件
	'TMPL_MODULE_ACTION_DEPR'=>'_',// 默认模块和方法分割符
	'DEFAULT_AJAX_RETURN'=>'JSON',// 默认AJAX数据返回格式,可选JSON,XML
	'TMPL_VAR_IDENTIFY'=>'',// 模板node解析自动识别为obj,array
	'AUTO_ACCEPT_LANGUAGE'=>TRUE,// 自动侦测语言
	'DYHB_AUTH_KEY'=>'dyhb_auth_key',// 安全key
	//'RBAC_ROLE_TABLE'=>role',
	//'RBAC_USERROLE_TABLE'=>'roleuser',
	//'RBAC_ACCESS_TABLE'=>access',
	//'RBAC_NODE_TABLE'=>'node',
	//'USER_AUTH_ON'=>TRUE,
	//'NOT_AUTH_MODULE'=>',
	//'USER_AUTH_ON'=>TRUE,
	//'USER_AUTH_TYPE'=>1, 默认认证类型1登录认证2实时认证
	//'USER_AUTH_KEY'=>'auth_id', 用户认证SESSION标记
	//'ADMIN_AUTH_KEY'=>'administrator',
	//'USER_AUTH_MODEL'=>'user', 默认验证数据表模型
	//'AUTH_PWD_ENCODER'=>'md5', 用户认证密码加密方式
	//'USER_AUTH_GATEWAY'=>'/public/login', 默认认证网关
	//'NOT_AUTH_MODULE'=>'public', 默认无需认证模块
	//'REQUIRE_AUTH_MODULE'=>', 默认需要认证模块
	//'NOT_AUTH_ACTION'=>'', 默认无需认证操作
	//'REQUIRE_AUTH_ACTION'=>', 默认需要认证操作
	//'GUEST_AUTH_ON'=>FALSE, 是否开启游客授权访问
	//'GUEST_AUTH_ID'=>0, 游客的用户ID
	'RBAC_DATA_PREFIX'=>'rbac_data_prefix',// RBAC相关数据前缀
	'HTML_CACHE_ON'=>FALSE,// 默认关闭静态缓存
	'HTML_CACHE_TIME'=>86400,// 静态缓存有效期
	'HTML_READ_TYPE'=>0,// 静态缓存读取方式0readfile1跳转
	'HTML_FILE_SUFFIX'=>'.html',// 默认静态文件后缀
	'TIME_ZONE'=>'Asia/Shanghai',// 时区
	'COOKIE_PREFIX'=>'dyhb_',// cookie前缀
	'COOKIE_LANG_TEMPLATE_INCLUDE_APPNAME'=>TRUE,// 语言包和模板COOKIE是否包含应用名
	'COOKIE_DOMAIN'=>'',// cookie域名
	'COOKIE_PATH'=>'/',// cookie路径
	'COOKIE_EXPIRE'=>86400,// cookie默认过期时间一天
	'SESSION_PREFIX'=>'dyhb_',// session前缀 For the future
	'URL_MODEL'=>1,// 0为普通，1为PATHINFO，2为rewrite,3为兼容模式
	'START_ROUTER'=>FALSE,// 是否开启URL路由
	'URL_PATHINFO_MODEL'=>2,// 1：普通模式,2：智能模式
	'URL_PATHINFO_DEPR'=>'/',// url分割符
	'URL_HTML_SUFFIX'=>'',// 伪静态后缀
	'NOT_ALLOWED_EMPTYCONTROL_VIEW'=>FALSE,// 是否允许不存在模块的时候直接调用视图
	'NOT_ALLOWED_EMPTYACTION_VIEW'=>FALSE,// 是否允许不存在方法的时候直接调用视图
	'DEFAULT_APP'=>'home',// 默认应用
	'DEFAULT_CONTROL'=>'index',// 默认控制器
	'DEFAULT_ACTION'=>'index',// 默认方法
	'LOG_RECORD'=>FALSE,// 默认不记录日志
	'LOG_FILE_SIZE'=>2097152,// 日志文件大小限制
	'LOG_RECORD_LEVEL'=>'EMERG|ALERT|CRIT|ERR',// 允许记录的日志级别
	'LOG_MUST_RECORD_EXCEPTION'=>FALSE,// 是否强制记录异常
	'LOG_SQL_ENABLED'=>FALSE,// 是否记录数据中的日志
	'SHOW_PAGE_TRACE'=>FALSE,// 显示页面调式信息
	'SHOW_RUN_TIME'=>FALSE,// 是否显示运行状态
	'SHOW_DETAIL_TIME'=>FALSE,// 是否显示运行时间
	'SHOW_USE_MEM'=>FALSE,// 系统运行是否显示内存
	'SHOW_DB_TIMES'=>FALSE,// 显示数据库查询次数
	'SHOW_GZIP_STATUS'=>FALSE,// 显示gzip状态
	'RUNTIME_CACHE_BACKEND'=>'FileCache',// 程序运行指定缓存
	'EMPTY_MODULE_NAME'=>'empty',// 系统预置空模块名字
	'EMPTY_ACTION_NAME'=>'empty_',// 系统预置空操作名字
	'ALLOWED_PROBE'=>TRUE,// 是否允许PHP探针
	'UPLOAD_FILE_RULE'=>'time',// 文件上传保存文件名函数
	'LANG_SWITCH'=>TRUE,// 是否允许切换语言包
	'LANG'=>'zh-cn',// 当前语言环境
	'URL_DOMAIN'=>'',// 域名，不为空将会被写入到生产的网址中，后面不能添加‘/’
	'_ROUTER_'=>array(), // 路由配置
	'_HTML_'=>array(), // HTML 静态化
);
